FROM python:3.12-slim

WORKDIR /app

COPY api/requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

COPY  api/app ./api/app

EXPOSE $PORT

CMD sh -c "uvicorn api.app.main:app --host 0.0.0.0 --port $PORT --reload"