version: '3.8'

services:
  spas_api_app:
    image: spas_api_app
    container_name: spas_system_api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Для разработки с hot-reload
    environment:
      - ENVIRONMENT=development